name: CI

on:
  push:
    paths:
    - 'ffq/**'
    - 'tests/**'

jobs:
  check-code:
    name: Check code quality
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: x64
      - name: Install dependencies
        run: pip install -r dev-requirements.txt
      - name: Check code quality
        run: make check
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [ '3.6', '3.7', '3.8', '3.9', '3.10']
        os: ['ubuntu-18.04']
    name: Test on Python ${{ matrix.python }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: pip install -r requirements.txt && pip install -r dev-requirements.txt
      - name: Run tests
        run: coverage run -m pytest -ra -v tests && coverage report --omit=main.py,tests*
